### ISSUE TITLE
Белый экран при запуске на локальной машине

### ISSUE THREAD

**Issue by progzone122** [ct-js/docs.ctjs.rocks#104]
При запуске сайта на локальной машине показывается белая страница и ошибка в консоли браузера "Загрузка модуля по адресу «http://localhost:8080/@id/C:/Users/Diablo/Documents/GitHub/docs.ctjs.rocks-russian/docs/.vuepress/.temp/internal/layoutComponents» была заблокирована из-за неразрешенного MIME-типа («»)."
![изображение](https://user-images.githubusercontent.com/80642969/210184178-002ae2a6-9234-4d49-9f33-e9027040f587.png)

**Comment by CosmoMyzrailGorynych** [comment]
Привет! Постепенно просыпаюсь после НГ. С наступившим!
Я обновил ряд зависимостей, обнови локальную ветку свою и сделай `npm install`. Попробуй после этого ещё раз.

**Comment by progzone122** [comment]
> Привет! Постепенно просыпаюсь после НГ. С наступившим! Я обновил ряд зависимостей, обнови локальную ветку свою и сделай `npm install`. Попробуй после этого ещё раз.

С прошедшим :)
Хорошо, гляну чуть позже

**Comment by progzone122** [comment]
Да, это у меня была проблема с зависимостями в ветке, issue закрыт.
