### ISSUE TITLE
Vuepress - automatic theme switching

### ISSUE THREAD

**Issue by hazarek** [ct-js/docs.ctjs.rocks#37]
Automatic theme switching does not work on https://docs.ctjs.rocks. When you type this into browser's console, the dark theme becomes active;
`document.body.classList.add('dark');`

And the colors of current dark theme are very bad(blueish high contrast tones). If you apply the theme below, it changes automatically according to the mode of the system. also the colors are better:
https://github.com/tolking/vuepress-theme-default-prefers-color-scheme

**Comment by CosmoMyzrailGorynych** [comment]
@hazarek The dark theme enables on ct.js' Night theme only, and it looks mostly in the way it was intended to be.
![изображение](https://user-images.githubusercontent.com/3174357/94070643-b40ae480-fe46-11ea-9e20-11761eadb483.png)

**Comment by hazarek** [comment]
@CosmoMyzrailGorynych i know, i'm talking about https://docs.ctjs.rocks. Why did you close without solving the problem.

> it looks mostly in the way it was intended to be.

You say "It's not a bug, it's a feature", Left-sliding panel overlaps with the interface(in tone with the background).

**Comment by naturecodevoid** [comment]
There's an outline for ct.IDE, and how would theme switching become "automatic"? It's not even fully supported, there are no buttons to change to dark mode and back.

**Comment by CosmoMyzrailGorynych** [comment]
> Automatic theme switching does not work on https://docs.ctjs.rocks
@hazarek There is no automatic theme switching at all, and never was. The dark theme you've discovered is for a specific theme in ct.IDE. The docs in ct.IDE are the same as at https://docs.ctjs.rocks.

> right-sliding panel overlaps with the interface(in tone with the background).
I don't quite understood what's wrong. Besides colors being different from ct.IDE, it looks as it should be. Could you highlight what is wrong, in your opinion?

**Comment by hazarek** [comment]
> There is no automatic theme switching at all, and never was. @CosmoMyzrailGorynych 

1. I know, I know, that's why I opened this issue anyway. I always use dark mode (macOS catalina). 
2. What is wrong?: https://docs.ctjs.rocks does not support [dark mode](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) in 2020. And this is wrong.

**Comment by CosmoMyzrailGorynych** [comment]
:facepalm: 

Then why do you describe something as a bug when you've intended to ask for a feature?

**Comment by CosmoMyzrailGorynych** [comment]
Also, this extension will evaporize all the blood bleeding from your eyes https://darkreader.org

**Comment by hazarek** [comment]
> Also, this extension will evaporize all the blood bleeding from your eyes https://darkreader.org

dark mode is not inverted colors, dark mode requires different implementation than light mode. i use Stylus themes if css is good designed. [more info](https://material.io/design/color/dark-theme.html);

**Comment by CosmoMyzrailGorynych** [comment]
@hazarek, honestly, it is naive and arrogant of you to think that your design skills are superior or whatsoever than mine, or of the other person, or that this or that a site should do something for your royal ass. 
In any way, I have no reasons to listen to you and follow your "must" or "must not". I have better stuff to do. And your "must" smells of an amateur level of skills. There are no "must", there are infinite brand and UX considerations, technical details, relations, and systems.

> dark mode is not inverted colors
you could at least look at darkreader's examples

**Comment by CosmoMyzrailGorynych** [comment]
Closed with an update to vuepress v2
