### ISSUE TITLE
Building your game and deployment to itch.io

### ISSUE THREAD

**Issue by NicBritz** [ct-js/docs.ctjs.rocks#68]
This is a sub-issue related to issue #43 
- Create a document section for building your game
- Create a subsection for deployment to itch.io ( can add more subsections at a later stage )

**Comment by CosmoMyzrailGorynych** [comment]
Closed in https://github.com/ct-js/docs.ctjs.rocks/commit/61b6c805bd4e73239b3cc3a10c24c80e5f2afd80 (PR #69)
